### ISSUE TITLE
Feature request: add GitLab pipeline web_url to outputs

### ISSUE THREAD

**Issue by nepalevov** [digital-blueprint/gitlab-pipeline-trigger-action#32]
Hi, and thank you for your development!

I suggest adding `web_url` for GitLab pipeline to action outputs. It will improve interactions with e.g. failed pipelines.

**Comment by pbek** [comment]
Can you please elaborate on your request? 😊

**Comment by pbek** [comment]
Maybe with a pull request? 😉

**Comment by nepalevov** [comment]
Done 🙂

**Comment by pbek** [comment]
Thank you! 👍️ I created a release.
