### ISSUE TITLE
With an invalid token this action gets stuck waiting forever

### ISSUE THREAD

**Issue by ludat** [digital-blueprint/gitlab-pipeline-trigger-action#34]
Maybe we should check the status code and throw an error if the gitlab api return unauthorized instead of keep trying

**Comment by pbek** [comment]
Good idea, do you care to add and test that?

**Comment by pbek** [comment]
I created a release https://github.com/digital-blueprint/gitlab-pipeline-trigger-action/releases/tag/v1.2.0.
Could you please test if it works for you?
