### ISSUE TITLE
Update v1 tag

### ISSUE THREAD

**Issue by lazka** [digital-blueprint/gitlab-pipeline-trigger-action#5]
The "official strategy" is to replace the v1 tag on each new v1.x release: https://github.com/actions/toolkit/blob/main/docs/action-versioning.md

**Comment by pbek** [comment]
I know, but aren't you also supposed to keep all the semver v*.*.* tags, like v1.0.1?

**Comment by lazka** [comment]
Yes. But v1 currently matches v1.0.0 instead of v1.0.1 from what I see.

**Comment by pbek** [comment]
Strange. Seems like that got messed up, I put v1 to main again. Thank you. There wasn't any functionality added anyway...

**Comment by lazka** [comment]
the tag is still the same

**Comment by lazka** [comment]
I've force pushed it now

**Comment by pbek** [comment]
My push never went trough. 😞 

```bash
git tag -fa v1 -m "Update v1 tag"
git push origin v1 --force
```

...did work now
